version: "2"
services:
  app:
    build: ./backend
    links:
      - db
    ports:
      - "5000:5000"
    environment:
      DBHOST: db 
      DBUSER: root
      DBPASSWORD: root

  db:
    image: mysql:5.7
    ports:
      - "32000:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./db:/docker-entrypoint-initdb.d/:ro
